services:
  - type: web
    name: odin-whereswaldo
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: aiven-postgres
          property: connectionString
